//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchDetails
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public int ItemQuantity { get; set; }
        public double ItemPrice { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.DateTime> OrderedOn { get; set; }
        public string OrderedBy { get; set; }
    
        public virtual StockBatch StockBatch { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
