//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrders()
        {
            this.CustomerOrderItems = new HashSet<CustomerOrderItems>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> OrderTotal { get; set; }
        public Nullable<int> OrderedItems { get; set; }
        public Nullable<System.DateTime> OrderedOn { get; set; }
        public Nullable<bool> isConfirmed { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderItems> CustomerOrderItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
